<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.app.vpk.</groupId>
		<artifactId>vpkservices</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<groupId>com.app.vpk.UILayer</groupId>
	<artifactId>UILayer</artifactId>
	<name>UILayer</name>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<description>Angular UILayer</description>
	<profiles>
		<profile>
			<id>default</id>
			<build>
				<resources>
					<resource>
						<directory>./</directory>
						<includes>
							<include>**/*</include>
						</includes>
					</resource>
				</resources>
				<plugins>
					<plugin>
						<groupId>com.github.eirslett</groupId>
						<artifactId>frontend-maven-plugin</artifactId>
						<version>1.12.1</version>

						<executions>
							<!-- Install Node.js and npm -->
							<execution>
								<id>install node and npm</id>
								<goals>
									<goal>install-node-and-npm</goal>
								</goals>
								<configuration>
									<nodeVersion>v12.14.1</nodeVersion>  <!-- Use the latest LTS version -->
									<npmVersion>6.13.4</npmVersion>
								</configuration>
							</execution>

							<!-- Install Angular dependencies -->
							<execution>
								<id>npm install</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>install</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>

							<!-- Build Angular App -->
							<execution>
								<id>npm build</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>run build</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>dev</id>
			<build>
				<resources>
					<resource>
						<directory>./</directory>
						<includes>
							<include>**/*</include>
						</includes>
					</resource>
				</resources>
				<plugins>
					<plugin>
						<groupId>com.github.eirslett</groupId>
						<artifactId>frontend-maven-plugin</artifactId>
						<version>1.12.1</version>

						<executions>
							<!-- Install Node.js and npm -->
							<execution>
								<id>install node and npm</id>
								<goals>
									<goal>install-node-and-npm</goal>
								</goals>
								<configuration>
									<nodeVersion>v12.14.1</nodeVersion>  <!-- Use the latest LTS version -->
									<npmVersion>6.13.4</npmVersion>
								</configuration>
							</execution>

							<!-- Install Angular dependencies -->
							<execution>
								<id>npm install</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>install</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>

							<!-- Build Angular App -->
							<execution>
								<id>npm build</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>run build:dev</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>test</id>
			<build>
				<resources>
					<resource>
						<directory>./</directory>
						<includes>
							<include>**/*</include>
						</includes>
					</resource>
				</resources>
				<plugins>
					<plugin>
						<groupId>com.github.eirslett</groupId>
						<artifactId>frontend-maven-plugin</artifactId>
						<version>1.12.1</version>

						<executions>
							<!-- Install Node.js and npm -->
							<execution>
								<id>install node and npm</id>
								<goals>
									<goal>install-node-and-npm</goal>
								</goals>
								<configuration>
									<nodeVersion>v12.14.1</nodeVersion>  <!-- Use the latest LTS version -->
									<npmVersion>6.13.4</npmVersion>
								</configuration>
							</execution>

							<!-- Install Angular dependencies -->
							<execution>
								<id>npm install</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>install</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>

							<!-- Build Angular App -->
							<execution>
								<id>npm build</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>run build:test</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>uat</id>
			<build>
				<resources>
					<resource>
						<directory>./</directory>
						<includes>
							<include>**/*</include>
						</includes>
					</resource>
				</resources>
				<plugins>
					<plugin>
						<groupId>com.github.eirslett</groupId>
						<artifactId>frontend-maven-plugin</artifactId>
						<version>1.12.1</version>

						<executions>
							<!-- Install Node.js and npm -->
							<execution>
								<id>install node and npm</id>
								<goals>
									<goal>install-node-and-npm</goal>
								</goals>
								<configuration>
									<nodeVersion>v12.14.1</nodeVersion>  <!-- Use the latest LTS version -->
									<npmVersion>6.13.4</npmVersion>
								</configuration>
							</execution>

							<!-- Install Angular dependencies -->
							<execution>
								<id>npm install</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>install</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>

							<!-- Build Angular App -->
							<execution>
								<id>npm build</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>run build:uat</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>preprod</id>
			<build>
				<resources>
					<resource>
						<directory>./</directory>
						<includes>
							<include>**/*</include>
						</includes>
					</resource>
				</resources>
				<plugins>
					<plugin>
						<groupId>com.github.eirslett</groupId>
						<artifactId>frontend-maven-plugin</artifactId>
						<version>1.12.1</version>

						<executions>
							<!-- Install Node.js and npm -->
							<execution>
								<id>install node and npm</id>
								<goals>
									<goal>install-node-and-npm</goal>
								</goals>
								<configuration>
									<nodeVersion>v12.14.1</nodeVersion>  <!-- Use the latest LTS version -->
									<npmVersion>6.13.4</npmVersion>
								</configuration>
							</execution>

							<!-- Install Angular dependencies -->
							<execution>
								<id>npm install</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>install</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>

							<!-- Build Angular App -->
							<execution>
								<id>npm build</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>run build:preprod</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>prod</id>
			<build>
				<resources>
					<resource>
						<directory>./</directory>
						<includes>
							<include>**/*</include>
						</includes>
					</resource>
				</resources>
				<plugins>
					<plugin>
						<groupId>com.github.eirslett</groupId>
						<artifactId>frontend-maven-plugin</artifactId>
						<version>1.12.1</version>

						<executions>
							<!-- Install Node.js and npm -->
							<execution>
								<id>install node and npm</id>
								<goals>
									<goal>install-node-and-npm</goal>
								</goals>
								<configuration>
									<nodeVersion>v12.14.1</nodeVersion>  <!-- Use the latest LTS version -->
									<npmVersion>6.13.4</npmVersion>
								</configuration>
							</execution>

							<!-- Install Angular dependencies -->
							<execution>
								<id>npm install</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>install</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>

							<!-- Build Angular App -->
							<execution>
								<id>npm build</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<configuration>
									<arguments>run build:prod</arguments>
									<workingDirectory>./</workingDirectory>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>