<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.app.vpk.</groupId>
		<artifactId>vpkservices</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<groupId>com.app.vpk.UILayer</groupId>
	<artifactId>UILayer</artifactId>
	<name>UILayer</name>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>
	<description>Angular UILayer</description>
	<build>
		<resources>
			<resource>
				<directory>./</directory>
				<includes>
					<include>**/*</include>
				</includes>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>1.12.1</version>

				<executions>
					<!-- Install Node.js and npm -->
					<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v12.14.1</nodeVersion>  <!-- Use the latest LTS version -->
							<npmVersion>6.13.4</npmVersion>
						</configuration>
					</execution>

					<!-- Install Angular dependencies -->
					<execution>
						<id>npm install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
							<workingDirectory>./</workingDirectory>
						</configuration>
					</execution>

					<!-- Build Angular App -->
					<execution>
						<id>npm build</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>run build</arguments>
							<workingDirectory>./</workingDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<!-- <plugin>
            <artifactId>maven-resources-plugin</artifactId>
            <version>3.2.0</version>
            <executions>
                <execution>
                    <id>copy-angular-to-static</id>
                    <phase>package</phase>
                    <goals>
                        <goal>copy-resources</goal>
                    </goals>
                    <configuration>
                        <outputDirectory>../ApiLayer/src/main/resources/static/</outputDirectory>
                        <resources>
                            <resource>
                                <directory>./</directory>
                                <filtering>false</filtering>
                            </resource>
                        </resources>
                    </configuration>
                </execution>
            </executions>
        </plugin> -->
		</plugins>
	</build>
</project>